### ISSUE TITLE
Decide on UIs to deploy for GFD and set up for demo

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea-proto#2]
I want to be clear on which UI(s) we are aiming to set up for the Holochain demo, and try to find the easiest path forward to getting something workable.

My current understanding of the situation is that we have multiple interfaces built by @ivanminutilo for the https://github.com/FreedomCoop/valuenetwork/ GraphQL API, and that the current interface in the `src/ui` folder has no backend connectivity. I would like to propose switching to one or more NRP UIs as I believe this will be less work than getting a fresh UI rigged up to talk to the backend.

I have ample bandwidth to work on the GraphQL API bindings for the Holochain backend, so I think between the three of us we should be able to cover this off pretty easily.

In any case: which UIs do we want to demo for the GFD, and can we integrate them with the project in a relatively simple manner?

**Comment by ivanminutillo** [comment]
Great to hear that you're willing to work on grahql integration.
If so, I can easily bind the UI that now lives on `src/ui` and have it ready in a couple of days.
That Ui is mostly made of components developed for the valuenetwork. 
I would suggest to finish the demo with that UI and in case it works good, refine them (I need to convert them in typescript, fairly easy to do) and push them into a common directory.

**Comment by pospi** [comment]
Sounds perfect, another UI to add to our repertoire! Ok, I will keep going on the GraphQL adapter work and set up some other tasks for the UI (:
